### ISSUE TITLE
Error: Cannot parse "data/tid/advancements/layer_2/enchant_max.json": JSON.parse: bad escaped character at line 9 column 130 of the JSON data.

### ISSUE THREAD

**Issue by Zungrysoft** [misode/upgrader#1]
An error occurred while loading a data pack.
Data Pack: 
[TED_2.zip](https://github.com/misode/upgrader/files/6604946/TED_2.zip)

```
a@https://misode.github.io/upgrader/assets/index.9a795188.js:1:20091

```

This happens with some other files as well, all of which are either loot tables or advancements.

**Comment by misode** [comment]
This is an issue with your data pack, the Minecraft JSON parser may ignore these errors but they're technically invalid JSON which this upgrader can't parse. In this case you need to remove the `\` before the single quote
![image](https://user-images.githubusercontent.com/17352009/120941200-ab7ee380-c721-11eb-9ae1-4da9cc5d511c.png)
