### ISSUE TITLE
Feature order cycle found. Needs manual fixing.

### ISSUE THREAD

**Issue by polylymer** [misode/upgrader#11]
what do you have to do with this error, unfortunately i don't know much about datapacks and am now stuck with this error (i have changed the order, but am in an endless loop)
![grafik](https://user-images.githubusercontent.com/74833245/152683601-1242cbc4-2460-4f55-845f-2a0afaccdcd5.png)

**Comment by misode** [comment]
That error means that in the `birch_forest` biome, `spring_water` is listed before `brown_mushroom_normal`, when it is the other way around in `extreme_hills`. You can fix this by swapping one of them, but it will depend on the order those features are used in other biomes.

To debug feature order cycles I recommend the Fabric mod [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric).
