### ISSUE TITLE
Datapack Upgrader [1.17.1]→[1.18.2] breaks the advancements

### ISSUE THREAD

**Issue by Felix14-v2** [misode/upgrader#19]
![image](https://user-images.githubusercontent.com/75726196/166106934-0d05ff1b-82b8-44e9-8ba0-5ffe06741f36.png)
After upgrading such advancements no longer works correctly.

<details>
 <summary>Advancement text</summary>

```shell
{
  "criteria": {
    "click_detect": {
      "trigger": "minecraft:player_interacted_with_entity",
      "conditions": {
        "player": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "player": {
                "looking_at": {
                  "type": "minecraft:area_effect_cloud",
                  "nbt": "{Tags:[button_area,settings_close]}"
                }
              }
            }
          }
        ],
        "entity": {
          "type": "minecraft:villager",
          "nbt": "{Tags:[touchscreen]}"
        }
      }
    }
  },
  "rewards": {
    "function": "settings:matrix/touchscreen/touch/settings_close"
  }
}

```
</details>

### Additional
[Example pack.zip](https://github.com/misode/misode.github.io/files/8596969/Example.pack.zip)

**Comment by misode** [comment]
@Felix14-v2 Just FYI, it looks like you selected 1.19 as the target to upgrade to, instead of 1.18.2 (indicated by the title)

**Comment by Felix14-v2** [comment]
It is excluded — I definitely chose version 1.18.2, I am 100% sure of it.

**Comment by misode** [comment]
Cannot reproduce, sorry. Please open a new issue if you have repro steps
