### ISSUE TITLE
/replaceitem is not converted to /item if it is inside an execute command

### ISSUE THREAD

**Issue by Zungrysoft** [misode/upgrader#2]
As can be seen in this file.
[eff_refill_healing_6.txt](https://github.com/misode/upgrader/files/6604951/eff_refill_healing_6.txt)

**Comment by misode** [comment]
🚀 A fix has been deployed. Thanks for reporting!

**Comment by campital** [comment]
This issue seems to persist for me at [misode.github.io/upgrader](https://misode.github.io/upgrader). For example, the following line does not change when upgraded: `execute if score @s armorItem matches 1 run replaceitem entity @s armor.head glass{Enchantments:[{id:"binding_curse",lvl:1}]}`.

**Comment by misode** [comment]
Thanks @campital, the issue is now again fixed!
