### ISSUE TITLE
Error: Cannot find "pack.mcmeta".

### ISSUE THREAD

**Issue by BTcreeper007** [misode/upgrader#4]
[Dynamics.zip](https://github.com/misode/upgrader/files/6618279/Dynamics.zip)
An error occurred while loading a data pack.
Data Pack: 

```
t@https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:20498
a@https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:20241
e.fromZip@https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:21320

```

**Comment by misode** [comment]
Hi, the zip contains a folder of the data pack, instead you should zip the `data` folder and the `pack.mcmeta` file together

**Comment by BTcreeper007** [comment]
This worked, thanks!
