### ISSUE TITLE
Drop file doesn't work on Linux

### ISSUE THREAD

**Issue by alex3236** [misode/upgrader#6]
The same datapack can be converted normally on Windows. But when I do the same thing on Linux, it says:
```
The dropped files contain no zip files. Please zip the data pack first.
```

Why not set a button to choose files in the file manager?

**Comment by eagle3236** [comment]
## Environment
```
OS: Archlinux
DE: Gnome
Browser: Chrome 92.0.4515.131
```

**Comment by misode** [comment]
Could you attach the file here that you are trying to convert?
